// utils/icon_mapper.dart
import 'package:flutter/material.dart';

class IconMapper {
  static const Map<String, IconData> _iconMap = {
    'star_outline': Icons.star_outline,
    'speed': Icons.speed,
    'functions': Icons.functions,
    'rotate_left': Icons.rotate_left,
    'alt_route': Icons.alt_route,
    'history': Icons.history,
    'memory': Icons.memory,
    'help_outline': Icons.help_outline,
    'lightbulb_outline': Icons.lightbulb_outline,
    'category': Icons.category,
    'settings': Icons.settings,
    'build': Icons.build,
    'calculate': Icons.calculate,
    'people': Icons.people,
    'insights': Icons.insights,
    'monitor_weight': Icons.monitor_weight,
    'straighten': Icons.straighten,
    'share': Icons.share,
    'warning_outlined': Icons.warning_outlined,
    'swap_horiz': Icons.swap_horiz,
    'medical_services': Icons.medical_services,
    'casino': Icons.casino,
    'trending_up': Icons.trending_up,
    'description': Icons.description,
    'info_outline': Icons.info_outline,
    'check_circle_outline': Icons.check_circle_outline,
    'error_outline': Icons.error_outline,
    'visibility': Icons.visibility,
    'visibility_off': Icons.visibility_off,
    'favorite_border': Icons.favorite_border,
    'favorite': Icons.favorite,
    'bookmark_border': Icons.bookmark_border,
    'bookmark': Icons.bookmark,
    'search': Icons.search,
    'add_circle_outline': Icons.add_circle_outline,
    'remove_circle_outline': Icons.remove_circle_outline,
    'edit': Icons.edit,
    'home': Icons.home,
    'person': Icons.person,
    'savings': Icons.savings,
    'business_center': Icons.business_center,
    'attach_money': Icons.attach_money,
    'tab': Icons.tab,
    'apps': Icons.apps,
    'flash_on': Icons.flash_on,
    'alarm': Icons.alarm,
    'local_offer': Icons.local_offer,
    'local_activity': Icons.local_activity,
    'local_library': Icons.local_library,
    'local_hospital': Icons.local_hospital,
    'restaurant': Icons.restaurant,
    'receipt': Icons.receipt,
    'compare_arrows': Icons.compare_arrows,
    'cake': Icons.cake,
    'info': Icons.info,
    'touch_app': Icons.touch_app,
    'aspect_ratio': Icons.aspect_ratio,
    'navigation': Icons.navigation,
    'map': Icons.map,
    'credit_card': Icons.credit_card,
    'tune': Icons.tune,
    'drag_handle': Icons.drag_handle,
    'filter_list': Icons.filter_list,
    'sort': Icons.sort,
    'view_agenda': Icons.view_agenda,
    'save': Icons.save,
    'update': Icons.update,
    'delete': Icons.delete,
    'center_focus_strong': Icons.center_focus_strong,
    'center_focus_weak': Icons.center_focus_weak,
    'precision_manufacturing': Icons.precision_manufacturing,
    'thermostat': Icons.thermostat,
    'science': Icons.science,
    'access_time': Icons.access_time,
    'storage': Icons.storage,
    'cloud_upload': Icons.cloud_upload,
    'cloud_download': Icons.cloud_download,
    'cloud_off': Icons.cloud_off,
    'rotate_90_degrees_ccw': Icons.rotate_90_degrees_ccw,
    'crop_free': Icons.crop_free,
    'fitness_center': Icons.fitness_center,
    'code': Icons.code,
    'devices': Icons.devices,
    'send': Icons.send,
    'security': Icons.security,
    'notifications': Icons.notifications,
    'folder': Icons.folder,
    'lock': Icons.lock,
    'bolt': Icons.bolt,
    'layers': Icons.layers,
    'play_circle': Icons.play_circle_fill,
    'check': Icons.check,
    'close': Icons.close,
    'warning': Icons.warning,
    'error': Icons.error,
    'network_wifi': Icons.network_wifi,
    'lan': Icons.lan,
    'chat': Icons.chat,
    'content_copy': Icons.content_copy,
    'palette': Icons.palette,
    'language': Icons.language,
    'phone_android': Icons.phone_android,
    'compress': Icons.compress,
    'message': Icons.message,
    'image': Icons.image,
    'attach_file': Icons.attach_file,
    'timer': Icons.timer,
    'schedule': Icons.schedule,
    'delete_forever': Icons.delete_forever,
    'keyboard': Icons.keyboard
  };

  static const Map<String, Color> _colorMap = {
    'amber': Colors.amber,
    'orange': Colors.orange,
    'blue': Colors.blue,
    'green': Colors.green,
    'purple': Colors.purple,
    'indigo': Colors.indigo,
    'teal': Colors.teal,
    'grey': Colors.grey,
    'red': Colors.red,
    'cyan': Colors.cyan,
  };

  static IconData getIcon(String name) {
    return _iconMap[name] ?? Icons.help; // Icon mặc định
  }

  static Color getColor(String name) {
    return _colorMap[name] ?? Colors.black; // Màu mặc định
  }
}
